name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"

      - name: Pip install
        run: pip install poetry

      - name: Poetry install
        run: poetry install

      - name: Pytest
        run: poetry run pytest -x -v --cov
